import type { Metadata } from "next";
import {Raleway} from "next/font/google";
import "./globals.css";


const raleway = Raleway({
    subsets: ['latin'],
    variable: '--raleway-font'
})

export const metadata: Metadata = {
  title: "ClearTek Systems",
  description: "Generated by create next app",
};

export const viewport = "width=device-width, initial-scale=1.0";

export default function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable}  antialiased  w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
